# Generated by Django 4.1 on 2023-04-10 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=120)),
                ('pdfLink', models.CharField(max_length=250)),
                ('pagesNo', models.IntegerField()),
                ('fileSizeKB', models.BigIntegerField()),
                ('uploadDateTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('repeatTimes', models.IntegerField()),
                ('pdfID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfDocs.pdfdocument')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentenceText', models.CharField(max_length=1000)),
                ('pageNumber', models.IntegerField()),
                ('pdfID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfDocs.pdfdocument')),
            ],
        ),
    ]
