# Generated by Django 4.1 on 2023-04-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfDocs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='pageNumber',
        ),
    ]
